CXX = g++
RM = rm -f
CPPFLAGS = -g -O2
LDFLAGS = -g -O2
LDLIBS =  -framework Accelerate -larmadillo
INC = 

SRCS = AbstractNonlinearProblem.cpp \
       Fold.cpp \
       Driver.cpp

OBJS = $(subst .cpp,.o,$(SRCS))

all: Driver

Driver: $(OBJS) 
	$(CXX) $(LDFLAGS) -o Driver $(OBJS) $(LDLIBS) 

depend: .depend

.depend: $(SRCS)
	rm -f ./.depend
	$(CXX) $(CPPFLAGS) $(INC) -MM $^>>./.depend;

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) *~ .depend

include .depend
